/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	yugabytedbrookiov1alpha1 "github.com/rook/rook/pkg/apis/yugabytedb.rook.io/v1alpha1"
	versioned "github.com/rook/rook/pkg/client/clientset/versioned"
	internalinterfaces "github.com/rook/rook/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/rook/rook/pkg/client/listers/yugabytedb.rook.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// YugabyteDBClusterInformer provides access to a shared informer and lister for
// YugabyteDBClusters.
type YugabyteDBClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.YugabyteDBClusterLister
}

type yugabyteDBClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewYugabyteDBClusterInformer constructs a new informer for YugabyteDBCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewYugabyteDBClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredYugabyteDBClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredYugabyteDBClusterInformer constructs a new informer for YugabyteDBCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredYugabyteDBClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.YugabytedbV1alpha1().YugabyteDBClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.YugabytedbV1alpha1().YugabyteDBClusters(namespace).Watch(options)
			},
		},
		&yugabytedbrookiov1alpha1.YugabyteDBCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *yugabyteDBClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredYugabyteDBClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *yugabyteDBClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&yugabytedbrookiov1alpha1.YugabyteDBCluster{}, f.defaultInformer)
}

func (f *yugabyteDBClusterInformer) Lister() v1alpha1.YugabyteDBClusterLister {
	return v1alpha1.NewYugabyteDBClusterLister(f.Informer().GetIndexer())
}
