/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/rook/rook/pkg/apis/yugabytedb.rook.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeYugabyteDBClusters implements YugabyteDBClusterInterface
type FakeYugabyteDBClusters struct {
	Fake *FakeYugabytedbV1alpha1
	ns   string
}

var yugabytedbclustersResource = schema.GroupVersionResource{Group: "yugabytedb.rook.io", Version: "v1alpha1", Resource: "yugabytedbclusters"}

var yugabytedbclustersKind = schema.GroupVersionKind{Group: "yugabytedb.rook.io", Version: "v1alpha1", Kind: "YugabyteDBCluster"}

// Get takes name of the yugabyteDBCluster, and returns the corresponding yugabyteDBCluster object, and an error if there is any.
func (c *FakeYugabyteDBClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.YugabyteDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(yugabytedbclustersResource, c.ns, name), &v1alpha1.YugabyteDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YugabyteDBCluster), err
}

// List takes label and field selectors, and returns the list of YugabyteDBClusters that match those selectors.
func (c *FakeYugabyteDBClusters) List(opts v1.ListOptions) (result *v1alpha1.YugabyteDBClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(yugabytedbclustersResource, yugabytedbclustersKind, c.ns, opts), &v1alpha1.YugabyteDBClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.YugabyteDBClusterList{ListMeta: obj.(*v1alpha1.YugabyteDBClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.YugabyteDBClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested yugabyteDBClusters.
func (c *FakeYugabyteDBClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(yugabytedbclustersResource, c.ns, opts))

}

// Create takes the representation of a yugabyteDBCluster and creates it.  Returns the server's representation of the yugabyteDBCluster, and an error, if there is any.
func (c *FakeYugabyteDBClusters) Create(yugabyteDBCluster *v1alpha1.YugabyteDBCluster) (result *v1alpha1.YugabyteDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(yugabytedbclustersResource, c.ns, yugabyteDBCluster), &v1alpha1.YugabyteDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YugabyteDBCluster), err
}

// Update takes the representation of a yugabyteDBCluster and updates it. Returns the server's representation of the yugabyteDBCluster, and an error, if there is any.
func (c *FakeYugabyteDBClusters) Update(yugabyteDBCluster *v1alpha1.YugabyteDBCluster) (result *v1alpha1.YugabyteDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(yugabytedbclustersResource, c.ns, yugabyteDBCluster), &v1alpha1.YugabyteDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YugabyteDBCluster), err
}

// Delete takes name of the yugabyteDBCluster and deletes it. Returns an error if one occurs.
func (c *FakeYugabyteDBClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(yugabytedbclustersResource, c.ns, name), &v1alpha1.YugabyteDBCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeYugabyteDBClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(yugabytedbclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.YugabyteDBClusterList{})
	return err
}

// Patch applies the patch and returns the patched yugabyteDBCluster.
func (c *FakeYugabyteDBClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.YugabyteDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(yugabytedbclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.YugabyteDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YugabyteDBCluster), err
}
